[tool.black]
line-length = 100
skip-string-normalization = true
target-version = ['py310']
exclude = '''

(
  /(
      \.eggs
    | \.git
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | build
    | dist
  )/
)
'''
