name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run SSH Agent
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.BUILDS_PRIVATE_SSH_KEY }}
    - name: Debug SSH agent
      run: |
        ssh-add -l
        echo SSH_AUTH_SOCK is at $SSH_AUTH_SOCK
    - uses: actions/setup-python@v1
      with:
        python-version: "3.10"
    - uses: dschep/install-pipenv-action@v1
    - name: Install project dependencies
      run: pipenv --bare sync --dev && pipenv graph --bare
    - name: pre-commit
      run: |
        echo "Running in: $(pwd)"
        echo "pre-commit hash: [$(sha256sum ./.pre-commit-config.yaml)]"
        echo "Pipenv project home: $(pipenv --where)"
        echo "Pipenv virtualenv: $(pipenv --venv)"
        echo "Pipenv interpreter: $(pipenv --py)"
        echo "Pipenv version: $(pipenv --version)"
        pipenv run check-all -a --show-diff-on-failure --color=always
